### ISSUE TITLE
Import files at correct places

### ISSUE THREAD

**Issue by rathorevaibhav** [gaurish-saini/E-Library#10]
After changing to `style.css` and `script.js`, move them to correct places. They should not be imported randomly at any line after doing some research.
![image](https://user-images.githubusercontent.com/12053186/114869099-3d4e2c80-9e14-11eb-9a88-4346625662bf.png)

**Comment by gaurish-saini** [comment]
Closing as default branch changed to master, solved this issue while implementing MVC design pattern, and will be including files at right places while further converting code structure into MVC.
