### ISSUE TITLE
Indentatiion

### ISSUE THREAD

**Issue by YaminiNegi** [gaurish-saini/E-Library#11]
Please give indentations wherever required.
![image](https://user-images.githubusercontent.com/64059807/119762290-0bc48880-becb-11eb-8ac1-a941d0be71ae.png)
![image](https://user-images.githubusercontent.com/64059807/119763115-85a94180-becc-11eb-8f2d-a56398e2d54d.png)

**Comment by gaurish-saini** [comment]
Closing as indentation practice is followed and is applied best of my knowledge. Editor view might differ in some cases.
