### ISSUE TITLE
Confusion in file names

### ISSUE THREAD

**Issue by rathorevaibhav** [gaurish-saini/E-Library#4]
There's confusion in some file names. Not able to understand what that file does.
1. add.php and ayourbook.php
2. rdetail.php
3. ryourbook.php
![image](https://user-images.githubusercontent.com/12053186/114866210-eabf4100-9e10-11eb-9948-1474571ca51d.png)

You need to work on your code structure and make sure files are in correct directories.

**Comment by gaurish-saini** [comment]
> There's confusion in some file names. Not able to understand what that file does.
> 
> 1. add.php and ayourbook.php
> 2. rdetail.php
> 3. ryourbook.php
>    ![image](https://user-images.githubusercontent.com/12053186/114866210-eabf4100-9e10-11eb-9948-1474571ca51d.png)
> 
> You need to work on your code structure and make sure files are in correct directories.

**Comment by gaurish-saini** [comment]
> > There's confusion in some file names. Not able to understand what that file does.
> > 
> > 1. add.php and ayourbook.php
> > 2. rdetail.php
> > 3. ryourbook.php
> >    ![image](https://user-images.githubusercontent.com/12053186/114866210-eabf4100-9e10-11eb-9948-1474571ca51d.png)
> > 
> > You need to work on your code structure and make sure files are in correct directories.

Moved code to MVC with better filenames and what it does, and reusing the code
