### ISSUE TITLE
Duplicate header files

### ISSUE THREAD

**Issue by rathorevaibhav** [gaurish-saini/E-Library#7]
There are two header files: header.php & addheader.php

There should be just one header template and we should follow DRY principle.

To show/hide add button, use an if/else statement inside single header file.
![image](https://user-images.githubusercontent.com/12053186/114867348-51912a00-9e12-11eb-93da-f30b746e463f.png)

**Comment by gaurish-saini** [comment]
Closing as default branch changed to master, solved this issue while implementing MVC design pattern.
Moved common files into E-Library/view/common/
