### ISSUE TITLE
Too many commented lines

### ISSUE THREAD

**Issue by rathorevaibhav** [gaurish-saini/E-Library#8]
https://github.com/gaurish-saini/E-Library/blob/main/index.php

Please check if these commented lines are needed or not. If not, let's remove them.

**Comment by gaurish-saini** [comment]
> https://github.com/gaurish-saini/E-Library/blob/main/index.php
> 
> Please check if these commented lines are needed or not. If not, let's remove them.

Closing as enhancing the code quality while shifting file structure to MVC
