### ISSUE TITLE
Explaination required

### ISSUE THREAD

**Issue by rathorevaibhav** [gaurish-saini/E-Library#9]
Please explain the purpose of this if statement and the condition being checked.
1. Why do you need this?
2. Should it be in `session.php`?

![image](https://user-images.githubusercontent.com/12053186/114868467-923d7300-9e13-11eb-9504-dd4d19e010a6.png)

**Comment by gaurish-saini** [comment]
Closing this as this concept and file is no longer required in new file structure of the application (master branch).
